# Generated by Django 5.0.6 on 2024-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mc_comments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reckwkwordid",
                    models.CharField(
                        blank=True,
                        max_length=505,
                        null=True,
                        verbose_name="记录ID关联到记录",
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=460,
                        null=True,
                        verbose_name="用户ID关联到用户",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="评论内容"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="评论状态如审核通过、待审核、删除",
                    ),
                ),
                (
                    "parentid",
                    models.TextField(
                        blank=True, null=True, verbose_name="父评论ID用于构建评论树"
                    ),
                ),
                (
                    "likes",
                    models.CharField(
                        blank=True, max_length=720, null=True, verbose_name="点赞数"
                    ),
                ),
            ],
            options={
                "verbose_name": "评论表",
                "verbose_name_plural": "评论表",
                "db_table": "comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_logs",
            fields=[
                (
                    "objectid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="操作对象ID如记录ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=580,
                        null=True,
                        verbose_name="用户ID关联到用户",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=980, null=True, verbose_name="操作类型"
                    ),
                ),
                (
                    "objecttype",
                    models.CharField(
                        blank=True,
                        max_length=505,
                        null=True,
                        verbose_name="操作对象类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "ipaddressip",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="日志状态如正常、异常",
                    ),
                ),
            ],
            options={
                "verbose_name": "日志表",
                "verbose_name_plural": "日志表",
                "db_table": "logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_permkwkwissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=965, null=True, verbose_name="权限名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "systemmodule",
                    models.CharField(
                        blank=True,
                        max_length=685,
                        null=True,
                        verbose_name="所属系统模块",
                    ),
                ),
                (
                    "actiontype",
                    models.CharField(
                        blank=True,
                        max_length=605,
                        null=True,
                        verbose_name="动作类型如增删改查",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        blank=True, max_length=630, null=True, verbose_name="资源标识"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=980,
                        null=True,
                        verbose_name="权限状态如启用、禁用",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限表",
                "verbose_name_plural": "权限表",
                "db_table": "permkwkwissions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_reckwkwordattachments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reckwkwordid",
                    models.CharField(
                        blank=True,
                        max_length=975,
                        null=True,
                        verbose_name="记录ID关联到记录",
                    ),
                ),
                (
                    "filename",
                    models.FileField(
                        blank=True, null=True, upload_to="57561", verbose_name="文件名"
                    ),
                ),
                (
                    "filepath",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57562",
                        verbose_name="文件存储路径",
                    ),
                ),
                (
                    "filesize",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57563",
                        verbose_name="文件大小",
                    ),
                ),
                (
                    "filetype",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57564",
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "uploadtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "uploaderid",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="上传者ID关联到用户",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "记录附件表",
                "verbose_name_plural": "记录附件表",
                "db_table": "reckwkwordattachments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_reckwkwordcategkwkwories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=770, null=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "parentid",
                    models.CharField(
                        blank=True,
                        max_length=725,
                        null=True,
                        verbose_name="关联父分类ID用于构建分类树",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwordernumber",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="显示顺序"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=535,
                        null=True,
                        verbose_name="分类状态如启用、禁用",
                    ),
                ),
            ],
            options={
                "verbose_name": "记录分类表",
                "verbose_name_plural": "记录分类表",
                "db_table": "reckwkwordcategkwkwories",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_reckwkwords",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=685, null=True, verbose_name="记录标题"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="记录内容"),
                ),
                (
                    "categkwkworyid",
                    models.CharField(
                        blank=True,
                        max_length=755,
                        null=True,
                        verbose_name="分类ID关联到记录分类",
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="创建者ID关联到用户",
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=685,
                        null=True,
                        verbose_name="记录状态如公开、私有",
                    ),
                ),
                (
                    "views",
                    models.CharField(
                        blank=True, max_length=490, null=True, verbose_name="浏览次数"
                    ),
                ),
            ],
            options={
                "verbose_name": "记录表",
                "verbose_name_plural": "记录表",
                "db_table": "reckwkwords",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_roles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rolename",
                    models.CharField(
                        blank=True, max_length=475, null=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "permkwkwissions",
                    models.CharField(
                        blank=True,
                        max_length=880,
                        null=True,
                        verbose_name="权限如JSON格式",
                    ),
                ),
                (
                    "kwkwiskwkwdefault",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否为默认角色"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="角色状态如启用、禁用",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色表",
                "verbose_name_plural": "角色表",
                "db_table": "roles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_supermanager",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=690, null=True, verbose_name="管理员姓名"
                    ),
                ),
            ],
            options={
                "verbose_name": "系统管理员",
                "verbose_name_plural": "系统管理员",
                "db_table": "supermanager",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=870, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "pkwkwasswkwkword",
                    models.CharField(
                        blank=True,
                        max_length=430,
                        null=True,
                        verbose_name="密码加密存储",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=490, null=True, verbose_name="电子邮件"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=965, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "lkwkwastlogkwkwintime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=615,
                        null=True,
                        verbose_name="用户状态如活跃、禁用",
                    ),
                ),
                (
                    "roleid",
                    models.CharField(
                        blank=True,
                        max_length=865,
                        null=True,
                        verbose_name="角色ID关联到角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
